//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura.Data.SqlServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_reserva
    {
        public int idDetReserva { get; set; }
        public string fk_num_habi { get; set; }
        public int fk_id_reserva { get; set; }
        public int estado_det { get; set; }
    
        public virtual habitacion habitacion { get; set; }
        public virtual reserva reserva { get; set; }
    }
}
