//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura.Data.SqlServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class habitacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public habitacion()
        {
            this.detalle_reserva = new HashSet<detalle_reserva>();
        }
    
        public string num_habi { get; set; }
        public string desc_habi { get; set; }
        public decimal precio_habi { get; set; }
        public int cat_id { get; set; }
        public int id_piso { get; set; }
        public string img_habi { get; set; }
        public string estado_habi { get; set; }
    
        public virtual categoria_habitacion categoria_habitacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_reserva> detalle_reserva { get; set; }
        public virtual piso piso { get; set; }
    }
}
