//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura.Data.SqlServer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbhotelEntities : DbContext
    {
        public dbhotelEntities()
            : base("name=dbhotelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categoria_habitacion> categoria_habitacion { get; set; }
        public virtual DbSet<clientes> clientes { get; set; }
        public virtual DbSet<detalle_reserva> detalle_reserva { get; set; }
        public virtual DbSet<habitacion> habitacion { get; set; }
        public virtual DbSet<piso> piso { get; set; }
        public virtual DbSet<reserva> reserva { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
